image: mreichelt/android:29

before_script:
  - chmod +x ./gradlew


stages:
  - build
  - deploy

build: 
    stage: build 
    script:
    - ./gradlew assembleDebug
    artifacts:
       paths:
       - app/build/outputs/
    
pages:
  stage: deploy
  script:
  - ./gradlew dokka 
  