image: mreichelt/android:29

before_script:
  - chmod +x ./gradlew


stages:
  - build
  - test
  - deploy

build: 
    stage: build 
    script:
    - ./gradlew assembleDebug
    artifacts:
       paths:
       - app/build/outputs/
       
       
       
       
tests:
    stage: test
    script:
       - ./gradlew test 


.connected-template: &connected-template
  stage: test
  image: registry.gitlab.com/fdroid/ci-images-client:latest
  script:
    - ./gradlew assemble 
    - start-emulator
    - wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest

    
pages:
  stage: deploy
  script:
  - ./gradlew dokka 
  - mv app/build/doc/app/ public/
  artifacts:
     paths:
      - public