image: mreichelt/android:29

before_script:
  - chmod +x ./gradlew


stages:
  - build
  - test
  - deploy

build: 
    stage: build 
    script:
    - ./gradlew assembleDebug
    artifacts:
       paths:
       - app/build/outputs/
       
       
       
       
tests:
    stage: test
    script:
       - ./gradlew test 


.connected-template: &connected-template
  stage: test
  image: openjdk
  script:
    - ./gradlew assemble 
    - start-emulator
    - wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest || (adb -e logcat -d > logcat.txt; exit 1)
  artifacts:
    paths:
      - logcat.txt

connected 22 default armeabi-v7a:
  <<: *connected-template

    
pages:
  stage: deploy
  script:
  - ./gradlew dokka 
  - mv app/build/doc/app/ public/
  artifacts:
     paths:
      - public